# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-25 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('md5_sum', models.CharField(max_length=255)),
                ('duration', models.FloatField(default=-1)),
                ('media_path', models.CharField(max_length=255)),
                ('thumbnail_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'amuze_media',
            },
        ),
    ]
